project_name: version

before:
  hooks:
    # 1) Ensure Conan profiles exist (idempotent).
    - bash -lc 'conan profile show -pr default >/dev/null 2>&1 || conan profile detect --force'
    # 2) Install tool_requires from conanfile.py and DEPLOY their binaries into ./.toolchain
    #    - We use the deploy generator to copy tool binaries into a local folder.
    #    - --build=missing lets CI bootstrap tools if cache is empty.
    - bash -lc 'mkdir -p .toolchain && conan install . -d full_deploy --deployer-folder=.toolchain --build=missing -s build_type=Release'
    # 3) Normalize PATH: collect all */bin under .toolchain into .toolchain/bin for a stable PATH entry.
    - bash -lc './buildtools/collect_bins.sh .toolchain'
    - go mod tidy
    # 4) Copy pre-built binaries to dist/ after cleanup
    - bash -lc 'if [ -d ".goreleaser-binaries" ]; then cp .goreleaser-binaries/* dist/ 2>/dev/null || true; fi'
    # 5) Create installer scripts for release
    - bash -lc './buildtools/create-simple-installers.sh {{ .Tag }}'

builds:
  - id: version
    main: ./cmd/version
    binary: version
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.appVersion={{ .Version }}

archives:
  - id: default
    builds: [version]
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ if eq .Os \"darwin\" }}macos{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - src: "packaging/linux/install.sh"
        dst: "install.sh"

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  draft: false
  extra_files:
    - glob: "installers/version-linux-*-install.sh"
    - glob: "installers/version-macos-*-install.sh"


scoop:
  bucket:
    owner: AlexBurnes
    name: scoop-bucket
    branch: main
  homepage: "https://github.com/AlexBurnes/version-go"
  description: "git describe-like CLI"
  license: "MIT"
  name: version
  commit_msg_template: "chore(scoop): update version to {{ .Tag }}"
  url_template: "https://github.com/AlexBurnes/version-go/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  skip_upload: false
  folder: "packaging/windows/scoop-bucket"

brews:
  - tap:
      owner: AlexBurnes
      name: homebrew-tap
      branch: main
    homepage: "https://github.com/AlexBurnes/version-go"
    description: "Cross-platform semantic version parsing, validation, and ordering CLI utility"
    license: "Apache-2.0"
    name: version
    commit_msg_template: "chore(homebrew): update version to {{ .Tag }}"
    url_template: "https://github.com/AlexBurnes/version-go/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    skip_upload: false
    folder: "packaging/macos"
    test: |
      system "#{bin}/version --version"
      system "#{bin}/version type 1.2.3"
      system "#{bin}/version type 1.2.3~alpha.1"
      system "#{bin}/version type 1.2.3.fix.1"
      system "#{bin}/version type 1.2.3_feature_1"
