project_name: version

before:
  hooks:
    # 1) Ensure Conan profiles exist (idempotent).
    - bash -lc 'conan profile show -pr default >/dev/null 2>&1 || conan profile detect --force'
    # 2) Install tool_requires from conanfile.py and DEPLOY their binaries into ./.toolchain
    #    - We use the deploy generator to copy tool binaries into a local folder.
    #    - --build=missing lets CI bootstrap tools if cache is empty.
    - bash -lc 'mkdir -p .toolchain && conan install . -d full_deploy --deployer-folder=.toolchain --build=missing -s build_type=Release'
    # 3) Normalize PATH: collect all */bin under .toolchain into .toolchain/bin for a stable PATH entry.
    - bash -lc './buildtools/collect_bins.sh .toolchain'
    - go mod tidy

builds:
  - id: version
    main: ./cmd/version
    binary: version
    env:
      # Expose Conan-deployed tools (go, cmake, ninja, etc.) to the GoReleaser build.
      - PATH={{ .Env.PATH }}:{{ .Env.PWD }}/.toolchain/bin
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/AlexBurnes/version-go/internal/buildinfo.Version={{ .Version }}
      - -X github.com/AlexBurnes/version-go/internal/buildinfo.Commit={{ .FullCommit }}
      - -X github.com/AlexBurnes/version-go/internal/buildinfo.Date={{ .Date }}
      - -X github.com/AlexBurnes/version-go/internal/buildinfo.Dirty={{ .IsGitDirty }}

archives:
  - id: default
    builds: [version]
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - src: "packaging/linux/install.sh"
        dst: "install.sh"

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
  draft: false

scoop:
  bucket:
    owner: AlexBurnes
    name: scoop-bucket
    branch: main
  homepage: "https://github.com/AlexBurnes/version-go"
  description: "git describe-like CLI"
  license: "MIT"
  name: version
  commit_msg_template: "chore(scoop): update version to {{ .Tag }}"
  url_template: "https://github.com/AlexBurnes/version-go/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  skip_upload: false
  folder: "packaging/windows/scoop-bucket"
